### ISSUE TITLE
Car Reservations Kanban Board

### ISSUE THREAD

**Issue by kaizipaul** [kaizipaul/full-stack-api#8]
### Kindly go through our project's Kanban board as we take on our full-stack project.
> There are Four(4) members on our team:
- @kaizipaul 
- @Ngufor-emmanuella 
- @AbayomiOlaoye 
- @Nowembabazi 

> Our Kanban board screenshot and link:
https://github.com/users/kaizipaul/projects/3/views/1
![image](https://user-images.githubusercontent.com/105969119/226351944-4fd003cf-1e7c-44b6-b2aa-a741f86b5045.png)

**Comment by Meltrust** [comment]
Hi @kaizipaul,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All tasks have been pointed and ssigned✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

### 1. According to the project requirements:

![image](https://user-images.githubusercontent.com/57421823/226360670-bda28d69-f0ae-4b00-97d7-d0e92a79ca04.png)

At the time of this review, these are the pointings:

Nowembabazi 24
Ngufor-emmanuella 27
kaizipaul 19
AbayomiOlaoye 24

Please take note that Kaizipaul has 8 less points than Ngufor-emmanuella.  Difference shouldn't be more than 5 points.

Therefore:

- [x] Kindly, ensure nobody in the team has more than 5 points than any other member.

Tip:  Just move around the pointings/tasks.

### 2. According to the project requirements:

![image](https://user-images.githubusercontent.com/57421823/226361990-28b387ae-8bb0-49db-913e-a668d498e564.png)

However, I can see that your tasks have no descriptions:

![image](https://user-images.githubusercontent.com/57421823/226362238-ca077308-1b15-4535-81ad-d64eba0b1aa9.png)

Therefore:

- [x] Kindly include descriptions in all the tasks in order to meet this particular requirement.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  
Good luck! 🎉 

## Highlights
- You've successfully implemented requested changes of the previous reviewer 👍 

## Optional suggestions
- Consider adding labels to your issues to help make them more descriptive and give ability to filter by type of issue 🤷‍♀️ 

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.


Cheers and Happy coding!👏👏👏


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
